//! CR-10 P1.6.1.2: emit the NodeCatalog JSON manifest
//! to stdout. The canonical regeneration path.
//!
//! Usage:
//!   cargo run -p astroforge-core --example emit_node_catalog > node_catalog.json
//!
//! The output goes to stdout so the caller can
//! redirect it; the checked-in manifest at
//! `crates/astroforge-core/src/node_catalog.json` is
//! regenerated by piping the output back into the
//! file. The slice's snapshot test pins the
//! checked-in manifest against the in-Rust source.

use astroforge_core::node_catalog::emit_catalog_json;

fn main() {
    println!("{}", emit_catalog_json());
}