// CR-10 P1.6.1.3 / Slice P1.6.1.3:
// NodeCatalog bridge (Rust -> TS).
//
// The catalog is the single source of truth for the
// 12 user-facing PipelineStageType variants. It is
// generated by Rust in
// `crates/astroforge-core/src/node_catalog.rs` and
// shipped to the TS side via the read-only
// `read_node_catalog` Tauri IPC.
//
// This module:
// 1. Defines the TS-side `NodeCatalog` and
//    `NodeCatalogEntry` interfaces that mirror the
//    Rust struct 1:1.
// 2. Provides `loadNodeCatalog()` that fetches the
//    catalog via `invoke('read_node_catalog')` and
//    caches it in module scope.
// 3. Provides `getCachedNodeCatalog()` for callers
//    that already have a loaded catalog (e.g. the
//    palette + constrained layout slices).
// 4. Provides `clearNodeCatalogCache()` for tests
//    + future reload-on-version-bump paths.
//
// The catalog is read-only at runtime; consumers
// must not mutate the loaded object.

import { invoke } from "@tauri-apps/api/core";

// ─── Types ──────────────────────────────────────────────────────────────────

/** Mirrors `astroforge_core::node_catalog::NodeCatalogEntry`. */
export interface NodeCatalogEntry {
  /** User-facing stage type, e.g. `color_calibration`. */
  stage_type: string;
  /** Human-readable label, e.g. `Colour Calibration / Balance`. */
  label: string;
  /** 1-2 sentence description (palette + tooltip + parameter panel header). */
  description: string;
  /** AI classification: true if the stage uses perceptual AI. */
  ai_uses_ai: boolean;
  /** AI model ID when `ai_uses_ai` is true (e.g. `astroforge_denoise_v1`). */
  ai_model_id: string | null;
  /** Whether the stage triggers the destructive re-apply warning. */
  destructive: boolean;
  /** Whether the stage writes a new ImageVersion. */
  produces_image_version: boolean;
  /** Whether the stage's pixels can be restored from params alone. */
  undo_supported: boolean;
  /** Default params JSON (consumed by the Parameter Panel on stage insert). */
  default_params: Record<string, unknown>;
  /** Supported AI model IDs (empty for classical stages). */
  supported_models: string[];
}

/** Mirrors `astroforge_core::node_catalog::NodeCatalog`. */
export interface NodeCatalog {
  /** Catalog version. Bumped when the schema changes. */
  version: number;
  /** Catalog entries, in user-facing stage-type order. */
  entries: NodeCatalogEntry[];
}

// ─── Cache ──────────────────────────────────────────────────────────────────

let cached: NodeCatalog | null = null;
let inflight: Promise<NodeCatalog> | null = null;

/**
 * Load the NodeCatalog from the Rust side via the
 * `read_node_catalog` IPC. Cached in module scope;
 * subsequent calls return the cached value.
 *
 * Concurrent calls share a single inflight
 * Promise — no thundering-herd, no duplicate
 * IPCs.
 *
 * Browser-mode fallback (no Tauri): returns an
 * empty catalog so the dev server keeps working.
 * Callers that depend on catalog presence must
 * gate behind `catalog.entries.length > 0`.
 */
export async function loadNodeCatalog(): Promise<NodeCatalog> {
  if (cached !== null) return cached;
  if (inflight !== null) return inflight;
  inflight = invoke<NodeCatalog>("read_node_catalog")
    .then((cat) => {
      cached = cat;
      inflight = null;
      return cat;
    })
    .catch((err) => {
      // Browser-mode fallback (no Tauri): the
      // invoke rejects with a Tauri IPC missing
      // error. Surface a clear empty catalog so
      // callers can degrade gracefully.
      inflight = null;
      if (
        err instanceof Error &&
        (err.message.includes("not available") ||
          err.message.includes("not registered"))
      ) {
        return { version: 0, entries: [] } satisfies NodeCatalog;
      }
      throw err;
    });
  return inflight;
}

/** Return the cached catalog if it exists, else null. */
export function getCachedNodeCatalog(): NodeCatalog | null {
  return cached;
}

/** Clear the cache. Used by tests; future reload-on-version-bump paths. */
export function clearNodeCatalogCache(): void {
  cached = null;
  inflight = null;
}

/**
 * CR-10 P1.6.2.4 / Slice P1.6.2.4:
 * Build a short tooltip summary from a catalog description.
 *
 * Returns the description verbatim when it is 7 words or
 * fewer, else returns the first 7 words followed by an
 * ellipsis. Returns the supplied `fallback` string when
 * the description is null, empty, or whitespace-only.
 *
 * Lives here (and not in the Svelte component) so the
 * truncation policy is testable in pure-vitest without a
 * Svelte render harness.
 */
export function shortSummary(
  description: string | null,
  fallback: string,
): string {
  if (description === null || description.trim().length === 0) {
    return fallback;
  }
  const words = description.trim().split(/\s+/);
  if (words.length <= 7) return words.join(" ");
  return words.slice(0, 7).join(" ") + "...";
}
