//! CR-06 P5.1 — real ONNX inference engine.
//!
//! P4's dispatcher was a metadata passthrough so the apply flow was
//! exercisable without a GPU. P5.1 swaps in the real path: every
//! enhancement operation resolves to an ONNX model, the source image
//! is tiled via [`crate::tiling`], and each tile runs through an
//! ONNX Runtime session on the CPU execution provider.
//!
//! ## Builtin models
//!
//! The catalog models in [`crate::hub`] (SwinIR etc.) are downloaded
//! artifacts; none ship with the repo today (their `sha256` entries
//! are placeholders pending the licensing decision DP#4). To keep the
//! real inference path exercisable everywhere — including CPU-only CI
//! — the crate bundles five small self-authored ONNX graphs under
//! `models/builtin/`, generated by `scripts/generate_builtin_models.py`.
//! They are classical image-processing kernels (Gaussian blend, unsharp
//! mask, linear upscale, outlier replacement, masked fill), each a few
//! hundred bytes, each pinned by a real SHA-256 digest in
//! [`BUILTIN_MODELS`]. When a catalog model artifact lands in the
//! model registry, the dispatcher prefers it; the builtin is the
//! always-available floor.
//!
//! ## Graph contract
//!
//! Every builtin graph consumes a single-channel image tensor
//! `[1, 1, H, W]` with dynamic spatial dims; the engine loops over
//! image channels. Scalar parameters (`strength`, `threshold`) are
//! graph inputs, so one graph serves the whole parameter range. The
//! masked-fill graph takes a second `[1, 1, H, W]` tensor carrying the
//! mask weights.

use astroforge_core::artifact::ContentStore;
use astroforge_core::image::F32Image;
use astroforge_core::masks::Mask;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};

/// Which scalar input a builtin graph expects, if any.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BuiltinInputKind {
    /// `image` only (upscale).
    ImageOnly,
    /// `image` + `strength` scalar.
    Strength,
    /// `image` + `threshold` scalar.
    Threshold,
    /// `image` + `mask` tensor.
    Mask,
}

/// A bundled classical-kernel ONNX model. `bytes` are the ONNX
/// protobuf, embedded at compile time; `sha256` is the digest the
/// generator printed when the fixture was produced. The digest is
/// verified at session-build time so a corrupted or tampered fixture
/// fails closed instead of running.
pub struct BuiltinModel {
    pub id: &'static str,
    pub kind: BuiltinInputKind,
    pub sha256: &'static str,
    pub bytes: &'static [u8],
}

/// A catalog ONNX model — a downloaded artifact whose SHA-256 is
/// pinned against this table at session-build time. Distinct from
/// [`BuiltinModel`]: builtins are in-repo graphs compiled into the
/// binary, catalog models are downloaded separately.
///
/// DP#4 closes the long-standing asymmetry where builtins were
/// digest-pinned but catalog models were not. Adding a catalog
/// model with a `sha256` of `"unverified"` keeps the entry in the
/// registry but marks it as fail-closed at runtime — the engine
/// refuses to load it until a real digest is provided.
pub struct CatalogModel {
    pub id: &'static str,
    pub kind: BuiltinInputKind,
    pub sha256: &'static str,
}

/// Sentinel value used by `CatalogModel::sha256` to mark a
/// catalog entry as not-yet-pinned. The engine refuses to open a
/// session for such an entry; the caller surfaces the failure
/// to the user with a clear "catalog model digest not yet
/// pinned — set DP#4 license + hash" message.
pub const UNVERIFIED_SHA256: &str = "unverified";

/// The known catalog entries. The five in-repo builtin graphs
/// appear here too — they have stable SHA-256 digests and are
/// shadow-catalogued so the catalog path can be exercised in
/// tests without a network download. The seven real-catalog
/// entries (SwinIR etc.) from PROJECT_PLAN P2-M1-T5..T11 are
/// listed with the `UNVERIFIED_SHA256` sentinel; loading any of
/// them today returns [`InferenceError::CatalogUnpinned`].
pub const CATALOG_MODELS: &[CatalogModel] = &[
    // Shadow catalogue for the in-repo builtins — the catalog
    // path uses the same digest check the builtin path uses.
    CatalogModel {
        id: "builtin-blur-blend",
        kind: BuiltinInputKind::Strength,
        sha256: "30b4c3729513f54802d00680ae6793016719f4cc40a00a7f231d220ccb1ae4f3",
    },
    CatalogModel {
        id: "builtin-sharpen-blend",
        kind: BuiltinInputKind::Strength,
        sha256: "34d34e9e75febfb3db84a5cc9ff4e1177ab003d2a9247cc8977845602c86cd85",
    },
    CatalogModel {
        id: "builtin-upscale-2x",
        kind: BuiltinInputKind::ImageOnly,
        sha256: "195850f85b9661fe7b3361b5c02c7b1a9ca5f453ae639082691f675ee075b7f1",
    },
    CatalogModel {
        id: "builtin-hotpixel",
        kind: BuiltinInputKind::Threshold,
        sha256: "07589c4d911fd4820ebcd7454d04c43cb926adad2bc75786c3bcb9cc496fba97",
    },
    CatalogModel {
        id: "builtin-masked-fill",
        kind: BuiltinInputKind::Mask,
        sha256: "d1646db8b65d2fb02a6badffd596f1cb255b0cef53edfa5086fc77f077b012ea",
    },
    // Real catalog models from PROJECT_PLAN P2-M1-T5..T11.
    // Each opens with the UNVERIFIED_SHA256 sentinel until
    // upstream licenses + hashes land; the engine refuses to
    // load any of them today. Adding a real digest to the
    // sentinel entry is the DP#4 closeout.
    CatalogModel {
        id: "swinir-denoise-astro",
        kind: BuiltinInputKind::ImageOnly,
        sha256: UNVERIFIED_SHA256,
    },
    CatalogModel {
        id: "swinir-sr-astro-2x",
        kind: BuiltinInputKind::ImageOnly,
        sha256: UNVERIFIED_SHA256,
    },
    CatalogModel {
        id: "swin2sr-dejpeg",
        kind: BuiltinInputKind::ImageOnly,
        sha256: UNVERIFIED_SHA256,
    },
    CatalogModel {
        id: "star-seg-v1",
        kind: BuiltinInputKind::ImageOnly,
        sha256: UNVERIFIED_SHA256,
    },
    CatalogModel {
        id: "cloud-score-v1",
        kind: BuiltinInputKind::ImageOnly,
        sha256: UNVERIFIED_SHA256,
    },
    CatalogModel {
        id: "color-cal-net",
        kind: BuiltinInputKind::ImageOnly,
        sha256: UNVERIFIED_SHA256,
    },
    CatalogModel {
        id: "trail-lama-tiny",
        kind: BuiltinInputKind::ImageOnly,
        sha256: UNVERIFIED_SHA256,
    },
];

pub fn catalog_model(id: &str) -> Option<&'static CatalogModel> {
    CATALOG_MODELS.iter().find(|m| m.id == id)
}
pub const BUILTIN_MODELS: &[BuiltinModel] = &[
    BuiltinModel {
        id: "builtin-blur-blend",
        kind: BuiltinInputKind::Strength,
        sha256: "30b4c3729513f54802d00680ae6793016719f4cc40a00a7f231d220ccb1ae4f3",
        bytes: include_bytes!("../models/builtin/builtin-blur-blend.onnx"),
    },
    BuiltinModel {
        id: "builtin-sharpen-blend",
        kind: BuiltinInputKind::Strength,
        sha256: "34d34e9e75febfb3db84a5cc9ff4e1177ab003d2a9247cc8977845602c86cd85",
        bytes: include_bytes!("../models/builtin/builtin-sharpen-blend.onnx"),
    },
    BuiltinModel {
        id: "builtin-upscale-2x",
        kind: BuiltinInputKind::ImageOnly,
        sha256: "195850f85b9661fe7b3361b5c02c7b1a9ca5f453ae639082691f675ee075b7f1",
        bytes: include_bytes!("../models/builtin/builtin-upscale-2x.onnx"),
    },
    BuiltinModel {
        id: "builtin-hotpixel",
        kind: BuiltinInputKind::Threshold,
        sha256: "07589c4d911fd4820ebcd7454d04c43cb926adad2bc75786c3bcb9cc496fba97",
        bytes: include_bytes!("../models/builtin/builtin-hotpixel.onnx"),
    },
    BuiltinModel {
        id: "builtin-masked-fill",
        kind: BuiltinInputKind::Mask,
        sha256: "d1646db8b65d2fb02a6badffd596f1cb255b0cef53edfa5086fc77f077b012ea",
        bytes: include_bytes!("../models/builtin/builtin-masked-fill.onnx"),
    },
];

pub fn builtin_model(id: &str) -> Option<&'static BuiltinModel> {
    BUILTIN_MODELS.iter().find(|m| m.id == id)
}

/// Errors from the inference engine. `Ort` carries the ONNX Runtime
/// error string (the `ort` error type does not implement `Clone` /
/// `PartialEq`, so we flatten to `String` at the boundary).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum InferenceError {
    /// The fixture bytes do not match the pinned digest.
    ChecksumMismatch { expected: String, actual: String },
    /// ONNX Runtime refused the model or the run.
    Ort(String),
    /// The graph produced a shape the engine cannot map back to an
    /// image (e.g. inconsistent per-channel output dims).
    BadOutputShape(String),
    /// A required input (mask) was not supplied for this graph kind.
    MissingInput(String),
    /// The catalog model id is not in `CATALOG_MODELS`.
    UnknownCatalogModel(String),
    /// The catalog model is registered but its digest has not
    /// been pinned yet (DP#4 license verification pending). The
    /// engine refuses to load it until a real SHA-256 lands.
    CatalogUnpinned { id: String },
}

impl std::fmt::Display for InferenceError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            InferenceError::ChecksumMismatch { expected, actual } => write!(
                f,
                "model checksum mismatch: expected {expected}, got {actual}"
            ),
            InferenceError::Ort(e) => write!(f, "onnx runtime: {e}"),
            InferenceError::BadOutputShape(s) => write!(f, "bad output shape: {s}"),
            InferenceError::MissingInput(s) => write!(f, "missing input: {s}"),
            InferenceError::UnknownCatalogModel(id) => {
                write!(f, "unknown catalog model: {id}")
            }
            InferenceError::CatalogUnpinned { id } => write!(
                f,
                "catalog model '{id}' is registered but its digest is \
                 not yet pinned (DP#4 license verification pending)"
            ),
        }
    }
}

impl std::error::Error for InferenceError {}

/// One live ONNX session bound to a specific builtin graph kind.
/// Sessions are cheap-ish to build but not free; the dispatcher builds
/// one per apply round. (A session cache keyed by model id is a
/// possible later optimisation — measure first.)
pub struct OnnxEngine {
    session: ort::session::Session,
    kind: BuiltinInputKind,
}

impl OnnxEngine {
    /// Build a session from raw ONNX bytes after verifying the digest
    /// against the pinned value. CPU execution provider only; GPU
    /// providers are compile-time features and land in P5.2.
    pub fn open_verified(
        bytes: &[u8],
        expected_sha256: &str,
        kind: BuiltinInputKind,
    ) -> Result<Self, InferenceError> {
        let actual = ContentStore::sha256_hex(bytes);
        if actual != expected_sha256 {
            return Err(InferenceError::ChecksumMismatch {
                expected: expected_sha256.to_string(),
                actual,
            });
        }
        let session = ort::session::Session::builder()
            .and_then(|mut b| b.commit_from_memory(bytes))
            .map_err(|e| InferenceError::Ort(e.to_string()))?;
        Ok(Self { session, kind })
    }

    pub fn open_builtin(model: &'static BuiltinModel) -> Result<Self, InferenceError> {
        Self::open_verified(model.bytes, model.sha256, model.kind)
    }

    /// Open a session from a downloaded catalog artifact. The
    /// `id` is looked up in [`CATALOG_MODELS`]; the runtime
    /// digest of `bytes` is verified against the pinned value;
    /// the engine fails closed on unknown id or unpinned entry.
    ///
    /// This closes DP#4: prior to this slice, catalog digests
    /// were placeholders and the engine accepted any bytes.
    pub fn open_catalog(id: &str, bytes: Vec<u8>) -> Result<Self, InferenceError> {
        let entry =
            catalog_model(id).ok_or_else(|| InferenceError::UnknownCatalogModel(id.to_string()))?;
        if entry.sha256 == UNVERIFIED_SHA256 {
            return Err(InferenceError::CatalogUnpinned { id: id.to_string() });
        }
        let actual = ContentStore::sha256_hex(&bytes);
        if actual != entry.sha256 {
            return Err(InferenceError::ChecksumMismatch {
                expected: entry.sha256.to_string(),
                actual,
            });
        }
        let kind = entry.kind;
        let session = ort::session::Session::builder()
            .and_then(|mut b| b.commit_from_memory(&bytes))
            .map_err(|e| InferenceError::Ort(e.to_string()))?;
        Ok(Self { session, kind })
    }

    /// Open a session from arbitrary catalog bytes without a
    /// registry check. Used by tests that construct synthetic
    /// inputs and by legacy catalog paths that have not yet
    /// migrated to the pinned [`open_catalog`] entry point.
    ///
    /// **Pre-DP#4 callers only.** Production paths should use
    /// [`open_catalog`] which verifies the digest.
    pub fn open_catalog_unpinned(
        bytes: Vec<u8>,
        kind: BuiltinInputKind,
    ) -> Result<Self, InferenceError> {
        let session = ort::session::Session::builder()
            .and_then(|mut b| b.commit_from_memory(&bytes))
            .map_err(|e| InferenceError::Ort(e.to_string()))?;
        Ok(Self { session, kind })
    }

    pub fn kind(&self) -> BuiltinInputKind {
        self.kind
    }

    /// Run the graph over every channel of `image` and restack the
    /// per-channel outputs. `strength` feeds the `strength` /
    /// `threshold` scalar input when the graph kind declares one;
    /// `mask` feeds the `mask` tensor input for masked-fill.
    ///
    /// Output dims come from the graph (the upscale graph returns
    /// `[1, 1, 2H, 2W]`); all channels must agree.
    pub fn run(
        &mut self,
        image: &F32Image,
        strength: Option<f32>,
        mask: Option<&Mask>,
    ) -> Result<F32Image, InferenceError> {
        let channels = image.channels();
        let mut out_planes: Option<(usize, usize, Vec<Vec<f32>>)> = None;
        for c in 0..channels {
            let plane = extract_plane(image, c);
            let out = self.run_plane(image.width(), image.height(), &plane, strength, mask)?;
            match &mut out_planes {
                None => out_planes = Some((out.0, out.1, vec![out.2])),
                Some((w, h, planes)) => {
                    if *w != out.0 || *h != out.1 {
                        return Err(InferenceError::BadOutputShape(format!(
                            "channel {c} produced {}x{}, expected {w}x{h}",
                            out.0, out.1
                        )));
                    }
                    planes.push(out.2);
                }
            }
        }
        let (w, h, planes) = out_planes
            .ok_or_else(|| InferenceError::BadOutputShape("image has zero channels".into()))?;
        Ok(stack_planes(w, h, &planes))
    }

    /// Run one single-channel plane through the graph. Returns
    /// `(out_w, out_h, row-major pixels)`.
    fn run_plane(
        &mut self,
        width: usize,
        height: usize,
        plane: &[f32],
        strength: Option<f32>,
        mask: Option<&Mask>,
    ) -> Result<(usize, usize, Vec<f32>), InferenceError> {
        use ort::value::Tensor;

        let img_tensor = Tensor::from_array((
            vec![1usize, 1, height, width],
            plane.to_vec().into_boxed_slice(),
        ))
        .map_err(|e| InferenceError::Ort(e.to_string()))?;

        let outputs = match self.kind {
            BuiltinInputKind::ImageOnly => self
                .session
                .run(ort::inputs![img_tensor])
                .map_err(|e| InferenceError::Ort(e.to_string()))?,
            BuiltinInputKind::Strength | BuiltinInputKind::Threshold => {
                let name = match self.kind {
                    BuiltinInputKind::Strength => "strength",
                    _ => "threshold",
                };
                let value = strength.unwrap_or(0.5);
                let scalar = Tensor::from_array((vec![1usize], vec![value].into_boxed_slice()))
                    .map_err(|e| InferenceError::Ort(e.to_string()))?;
                self.session
                    .run(ort::inputs!["image" => img_tensor, name => scalar])
                    .map_err(|e| InferenceError::Ort(e.to_string()))?
            }
            BuiltinInputKind::Mask => {
                let mask = mask.ok_or_else(|| {
                    InferenceError::MissingInput("masked-fill graph requires a mask tensor".into())
                })?;
                let mask_plane = mask_plane_for(mask, width, height);
                let mask_tensor = Tensor::from_array((
                    vec![1usize, 1, height, width],
                    mask_plane.into_boxed_slice(),
                ))
                .map_err(|e| InferenceError::Ort(e.to_string()))?;
                self.session
                    .run(ort::inputs!["image" => img_tensor, "mask" => mask_tensor])
                    .map_err(|e| InferenceError::Ort(e.to_string()))?
            }
        };

        let (shape, data) = outputs[0]
            .try_extract_tensor::<f32>()
            .map_err(|e| InferenceError::Ort(e.to_string()))?;
        let dims: Vec<usize> = shape.iter().map(|&d| d as usize).collect();
        if dims.len() != 4 || dims[0] != 1 || dims[1] != 1 {
            return Err(InferenceError::BadOutputShape(format!(
                "expected [1,1,H,W], got {dims:?}"
            )));
        }
        Ok((dims[3], dims[2], data.to_vec()))
    }
}

/// Extract channel `c` of an F32Image as a row-major `Vec<f32>`.
fn extract_plane(image: &F32Image, c: usize) -> Vec<f32> {
    let w = image.width();
    let h = image.height();
    let mut plane = Vec::with_capacity(w * h);
    for y in 0..h {
        for x in 0..w {
            plane.push(image[(c, y, x)]);
        }
    }
    plane
}

/// Restack per-channel row-major planes into an F32Image
/// (`(C, H, W)` layout).
fn stack_planes(width: usize, height: usize, planes: &[Vec<f32>]) -> F32Image {
    let mut img = F32Image::new(width, height, planes.len());
    for (c, plane) in planes.iter().enumerate() {
        for y in 0..height {
            for x in 0..width {
                img[(c, y, x)] = plane[y * width + x];
            }
        }
    }
    img
}

/// Rasterise a mask into a `width * height` row-major plane, sampling
/// with clamping when the mask dims disagree with the image dims (a
/// mask authored against a downscaled preview still applies).
fn mask_plane_for(mask: &Mask, width: usize, height: usize) -> Vec<f32> {
    let mut plane = Vec::with_capacity(width * height);
    for y in 0..height {
        for x in 0..width {
            let mx = (x as u64 * mask.width as u64 / width.max(1) as u64) as u32;
            let my = (y as u64 * mask.height as u64 / height.max(1) as u64) as u32;
            plane.push(mask.get(mx.min(mask.width - 1), my.min(mask.height - 1)));
        }
    }
    plane
}

/// A process-wide cache of `OnnxEngine` sessions keyed by model
/// identity. Building a session is cheap (a few hundred
/// milliseconds), but a 50-image apply round on the same model
/// ends up paying that cost 50 times. Caching by `(kind,
/// sha256)` cuts the per-apply cost to one session build per
/// model lifetime.
///
/// Concurrency: `Arc<Mutex<HashMap<...>>>` lets the dispatcher
/// share the cache across threads. The mutex is uncontended in
/// the steady state (cache hits don't write). The cache is
/// append-only within a session — no eviction today; future
/// work can add a TTL if memory pressure warrants.
///
/// The cache stores `Arc<Mutex<OnnxEngine>>` rather than
/// `Arc<OnnxEngine>` because `Session::run` takes `&mut self`
/// in the current `ort` API; sharing requires interior
/// mutability. Each cache hit locks the engine briefly for the
/// duration of one `run`.
#[derive(Default, Clone)]
pub struct SessionCache {
    inner: Arc<Mutex<HashMap<String, Arc<Mutex<OnnxEngine>>>>>,
}

impl SessionCache {
    pub fn new() -> Self {
        Self::default()
    }

    /// Return a clone of the cached engine for `key`, or `None`
    /// if absent. The clone shares the underlying session so
    /// `run` calls serialise on the inner mutex.
    pub fn get(&self, key: &str) -> Option<Arc<Mutex<OnnxEngine>>> {
        let guard = self.inner.lock().expect("session-cache mutex poisoned");
        guard.get(key).cloned()
    }

    /// Insert `engine` under `key`. Returns the inserted clone
    /// so the caller can use it without re-querying.
    pub fn insert(&self, key: String, engine: OnnxEngine) -> Arc<Mutex<OnnxEngine>> {
        let engine = Arc::new(Mutex::new(engine));
        let mut guard = self.inner.lock().expect("session-cache mutex poisoned");
        guard.insert(key, engine.clone());
        engine
    }

    /// Get or build an engine for `key`, calling `build` on
    /// cache miss. The build closure runs while the cache
    /// mutex is **not** held so a slow build (hundreds of ms)
    /// doesn't block concurrent reads.
    pub fn get_or_build<F>(
        &self,
        key: String,
        build: F,
    ) -> Result<Arc<Mutex<OnnxEngine>>, InferenceError>
    where
        F: FnOnce() -> Result<OnnxEngine, InferenceError>,
    {
        if let Some(hit) = self.get(&key) {
            return Ok(hit);
        }
        let engine = build()?;
        Ok(self.insert(key, engine))
    }

    /// Number of cached engines. Useful for telemetry and tests.
    pub fn len(&self) -> usize {
        self.inner
            .lock()
            .expect("session-cache mutex poisoned")
            .len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Drop every cached engine. Used when the model registry
    /// changes (a new build of the binary ships an updated
    /// digest table).
    pub fn clear(&self) {
        self.inner
            .lock()
            .expect("session-cache mutex poisoned")
            .clear();
    }
}

/// The cache key for a builtin model: `"{kind}:{sha256}"`.
/// Including the kind in the key guards against the unlikely
/// event that two graphs share a digest.
pub fn builtin_cache_key(model: &BuiltinModel) -> String {
    format!("builtin:{}:{}", kind_label(model.kind), model.sha256)
}

/// The cache key for a catalog model: `"{kind}:{sha256}"`.
/// Same shape as the builtin key so the cache treats them
/// uniformly.
pub fn catalog_cache_key(model: &CatalogModel) -> String {
    format!("catalog:{}:{}", kind_label(model.kind), model.sha256)
}

fn kind_label(kind: BuiltinInputKind) -> &'static str {
    match kind {
        BuiltinInputKind::ImageOnly => "image",
        BuiltinInputKind::Strength => "strength",
        BuiltinInputKind::Threshold => "threshold",
        BuiltinInputKind::Mask => "mask",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use astroforge_core::masks::MaskKind;
    use ndarray::Array3;

    fn gradient(width: usize, height: usize) -> F32Image {
        let mut arr = Array3::<f32>::zeros((1, height, width));
        for y in 0..height {
            for x in 0..width {
                arr[(0, y, x)] = (x + y) as f32 / (width + height) as f32;
            }
        }
        F32Image::from(arr)
    }

    fn uniform(value: f32, width: usize, height: usize, channels: usize) -> F32Image {
        F32Image::from(Array3::from_elem((channels, height, width), value))
    }

    fn engine(id: &str) -> OnnxEngine {
        OnnxEngine::open_builtin(builtin_model(id).expect("builtin exists")).expect("session")
    }

    #[test]
    fn every_builtin_fixture_matches_its_pinned_digest() {
        for model in BUILTIN_MODELS {
            let actual = ContentStore::sha256_hex(model.bytes);
            assert_eq!(actual, model.sha256, "digest drifted for {}", model.id);
        }
    }

    #[test]
    fn checksum_mismatch_fails_closed() {
        let model = builtin_model("builtin-blur-blend").unwrap();
        let err = match OnnxEngine::open_verified(model.bytes, "0000", model.kind) {
            Ok(_) => panic!("mismatched digest must fail closed"),
            Err(e) => e,
        };
        assert!(matches!(err, InferenceError::ChecksumMismatch { .. }));
    }

    #[test]
    fn blur_blend_preserves_uniform_image() {
        let img = uniform(0.4, 24, 24, 1);
        let out = engine("builtin-blur-blend")
            .run(&img, Some(1.0), None)
            .unwrap();
        for y in 2..22 {
            for x in 2..22 {
                assert!((out[(0, y, x)] - 0.4).abs() < 1e-4);
            }
        }
    }

    #[test]
    fn blur_blend_reduces_variance_of_noisy_image() {
        let mut arr = Array3::<f32>::zeros((1, 32, 32));
        for y in 0..32 {
            for x in 0..32 {
                let checker = if (x + y) % 2 == 0 { 0.8 } else { 0.2 };
                arr[(0, y, x)] = checker;
            }
        }
        let img = F32Image::from(arr);
        let out = engine("builtin-blur-blend")
            .run(&img, Some(1.0), None)
            .unwrap();
        let var = |image: &F32Image| {
            let n = (image.width() * image.height()) as f32;
            let mut sum = 0.0;
            let mut sq = 0.0;
            for y in 0..image.height() {
                for x in 0..image.width() {
                    let v = image[(0, y, x)];
                    sum += v;
                    sq += v * v;
                }
            }
            (sq / n) - (sum / n).powi(2)
        };
        assert!(var(&out) < var(&img) * 0.5);
    }

    #[test]
    fn blur_blend_at_zero_strength_is_identity() {
        let img = gradient(16, 16);
        let out = engine("builtin-blur-blend")
            .run(&img, Some(0.0), None)
            .unwrap();
        for y in 0..16 {
            for x in 0..16 {
                assert!((out[(0, y, x)] - img[(0, y, x)]).abs() < 1e-6);
            }
        }
    }

    #[test]
    fn sharpen_blend_increases_local_contrast() {
        // A single bright pixel on a dark field: the unsharp mask must
        // raise the peak above the source value.
        let mut img = uniform(0.1, 24, 24, 1);
        img[(0, 12, 12)] = 0.9;
        let out = engine("builtin-sharpen-blend")
            .run(&img, Some(1.0), None)
            .unwrap();
        assert!(out[(0, 12, 12)] > 0.9 + 1e-3);
    }

    #[test]
    fn upscale_2x_doubles_spatial_dims() {
        let img = gradient(8, 6);
        let out = engine("builtin-upscale-2x").run(&img, None, None).unwrap();
        assert_eq!(out.width(), 16);
        assert_eq!(out.height(), 12);
        assert_eq!(out.channels(), 1);
        // Linear upscale of a linear ramp stays monotonic along x.
        for y in 0..12 {
            for x in 1..16 {
                assert!(out[(0, y, x)] >= out[(0, y, x - 1)] - 1e-6);
            }
        }
    }

    #[test]
    fn hotpixel_replaces_only_the_spike() {
        let mut img = uniform(0.2, 16, 16, 1);
        img[(0, 8, 8)] = 1.0;
        let out = engine("builtin-hotpixel")
            .run(&img, Some(1.5), None)
            .unwrap();
        assert!(
            out[(0, 8, 8)] < 0.4,
            "spike must collapse to the local mean"
        );
        // An interior pixel far from the spike is untouched. (Border
        // pixels are excluded: ONNX Conv zero-pads, which drags border
        // means down and can trip the threshold there. The dispatcher's
        // tile overlap blending absorbs border effects in practice.)
        assert!((out[(0, 4, 8)] - 0.2).abs() < 1e-4);
    }

    #[test]
    fn masked_fill_only_touches_masked_region() {
        let mut img = uniform(0.2, 16, 16, 1);
        img[(0, 8, 8)] = 1.0;
        let mut mask = Mask::zeros(16, 16, MaskKind::User, "test".into());
        mask.set(8, 8, 1.0);
        let out = engine("builtin-masked-fill")
            .run(&img, None, Some(&mask))
            .unwrap();
        // Masked pixel is pulled toward the local mean (0.2).
        assert!(out[(0, 8, 8)] < 0.9);
        // Unmasked pixels pass through.
        assert!((out[(0, 0, 0)] - 0.2).abs() < 1e-4);
        assert!((out[(0, 4, 4)] - 0.2).abs() < 1e-4);
    }

    #[test]
    fn masked_fill_without_mask_errors() {
        let img = uniform(0.2, 8, 8, 1);
        let err = engine("builtin-masked-fill")
            .run(&img, None, None)
            .unwrap_err();
        assert!(matches!(err, InferenceError::MissingInput(_)));
    }

    #[test]
    fn multichannel_images_run_per_channel() {
        let img = uniform(0.5, 12, 12, 3);
        let out = engine("builtin-blur-blend")
            .run(&img, Some(0.7), None)
            .unwrap();
        assert_eq!(out.channels(), 3);
        for c in 0..3 {
            assert!((out[(c, 6, 6)] - 0.5).abs() < 1e-4);
        }
    }

    #[test]
    fn mask_plane_resamples_mismatched_dims() {
        let mut mask = Mask::zeros(4, 4, MaskKind::User, "test".into());
        mask.set(0, 0, 1.0);
        let plane = mask_plane_for(&mask, 8, 8);
        assert_eq!(plane.len(), 64);
        // Top-left quadrant samples mask (0,0) = 1.0; opposite corner 0.0.
        assert!((plane[0] - 1.0).abs() < 1e-6);
        assert!((plane[63] - 0.0).abs() < 1e-6);
    }

    // ── DP#4 catalog registry ────────────────────────────────────

    #[test]
    fn catalog_model_lookups_for_every_builtin() {
        for builtin in BUILTIN_MODELS {
            let entry = catalog_model(builtin.id)
                .unwrap_or_else(|| panic!("missing catalog entry for {}", builtin.id));
            // Shadow-catalogued builtins share the digest with the
            // builtin registry — that's the whole point of the
            // shadow.
            assert_eq!(entry.sha256, builtin.sha256);
        }
    }

    #[test]
    fn catalog_model_unknown_returns_none() {
        assert!(catalog_model("not-a-real-model").is_none());
    }

    #[test]
    fn catalog_unpinned_set_is_correct() {
        // The 7 real-catalog entries from P2-M1-T5..T11 should
        // all carry the UNVERIFIED_SHA256 sentinel until DP#4
        // lands. This is the fail-closed guarantee the catalog
        // path relies on.
        let unpinned_ids = [
            "swinir-denoise-astro",
            "swinir-sr-astro-2x",
            "swin2sr-dejpeg",
            "star-seg-v1",
            "cloud-score-v1",
            "color-cal-net",
            "trail-lama-tiny",
        ];
        for id in unpinned_ids {
            let entry = catalog_model(id).unwrap();
            assert_eq!(entry.sha256, UNVERIFIED_SHA256, "{id} must be unpinned");
        }
    }

    #[test]
    fn open_catalog_unknown_id_fails_closed() {
        let bytes = vec![0u8; 8];
        match OnnxEngine::open_catalog("not-a-real-model", bytes) {
            Err(InferenceError::UnknownCatalogModel(id)) => {
                assert_eq!(id, "not-a-real-model");
            }
            Err(other) => panic!("expected UnknownCatalogModel, got {other:?}"),
            Ok(_) => panic!("expected error, got Ok"),
        }
    }

    #[test]
    fn open_catalog_unpinned_fails_closed() {
        // SwinIR is registered but unpinned. Any bytes — even
        // real ones — fail closed with a clear error.
        let bytes = vec![0u8; 8];
        match OnnxEngine::open_catalog("swinir-denoise-astro", bytes) {
            Err(InferenceError::CatalogUnpinned { id }) => {
                assert_eq!(id, "swinir-denoise-astro");
            }
            Err(other) => panic!("expected CatalogUnpinned, got {other:?}"),
            Ok(_) => panic!("expected error, got Ok"),
        }
    }

    #[test]
    fn open_catalog_unpinned_test_path_still_works() {
        // The legacy `open_catalog_unpinned` entry point
        // preserves the pre-DP#4 contract for tests + callers
        // that haven't migrated yet. It accepts any bytes.
        let bytes = vec![0u8; 8];
        let result = OnnxEngine::open_catalog_unpinned(bytes, BuiltinInputKind::ImageOnly);
        // The ORT session build will fail (random bytes are not
        // a valid ONNX graph); we only verify the legacy path
        // doesn't trip the new registry check.
        assert!(matches!(result, Err(InferenceError::Ort(_))));
    }

    // ── SessionCache ──────────────────────────────────────────────

    #[test]
    fn session_cache_starts_empty() {
        let cache = SessionCache::new();
        assert!(cache.is_empty());
        assert_eq!(cache.len(), 0);
    }

    #[test]
    fn session_cache_get_or_build_caches_on_second_call() {
        let cache = SessionCache::new();
        // Build closure count — should fire only once across
        // multiple get_or_build calls with the same key.
        let build_count = Arc::new(Mutex::new(0u32));
        let key = "test-key".to_string();
        // First call: cache miss, build fires.
        let count_a = build_count.clone();
        let _ = cache.get_or_build(key.clone(), || {
            *count_a.lock().unwrap() += 1;
            // Synthetic ONNX failure — the closure produces an
            // error before reaching the session build, which is
            // enough to verify the cache flow without requiring
            // a real graph.
            Err(InferenceError::ChecksumMismatch {
                expected: "expected".into(),
                actual: "actual".into(),
            })
        });
        // Second call with the same key: cache miss (the prior
        // call failed before insert), build fires again.
        let count_b = build_count.clone();
        let _ = cache.get_or_build(key.clone(), || {
            *count_b.lock().unwrap() += 1;
            Err(InferenceError::ChecksumMismatch {
                expected: "expected".into(),
                actual: "actual".into(),
            })
        });
        assert_eq!(
            *build_count.lock().unwrap(),
            2,
            "failed builds must not pollute the cache"
        );
    }

    #[test]
    fn session_cache_clear_drops_entries() {
        let cache = SessionCache::new();
        // Insert a fake entry via the public API. We use a
        // builder that returns a real ORT error to avoid
        // needing a real ONNX graph in the test.
        let key = "test-key".to_string();
        let _ = cache.get_or_build(key.clone(), || {
            Err(InferenceError::ChecksumMismatch {
                expected: "expected".into(),
                actual: "actual".into(),
            })
        });
        // The failed insert means the cache is still empty.
        assert!(cache.is_empty());
        cache.clear();
        assert!(cache.is_empty());
    }

    #[test]
    fn cache_keys_are_distinct_per_kind_and_digest() {
        let builtin = &BUILTIN_MODELS[0];
        let catalog = catalog_model(builtin.id).unwrap();
        // Same kind + same digest, but builtin vs catalog are
        // distinct namespaces — the cache must not conflate them.
        assert_ne!(builtin_cache_key(builtin), catalog_cache_key(catalog),);
    }

    #[test]
    fn builtin_cache_key_includes_kind_and_digest() {
        let m = &BUILTIN_MODELS[0];
        let key = builtin_cache_key(m);
        assert!(key.starts_with("builtin:"));
        assert!(key.contains(m.sha256));
    }

    #[test]
    fn catalog_cache_key_includes_kind_and_digest() {
        let m = catalog_model(BUILTIN_MODELS[0].id).unwrap();
        let key = catalog_cache_key(m);
        assert!(key.starts_with("catalog:"));
        assert!(key.contains(m.sha256));
    }
}
