//! CR-06 P5.1 — real ONNX inference engine.
//!
//! P4's dispatcher was a metadata passthrough so the apply flow was
//! exercisable without a GPU. P5.1 swaps in the real path: every
//! enhancement operation resolves to an ONNX model, the source image
//! is tiled via [`crate::tiling`], and each tile runs through an
//! ONNX Runtime session on the CPU execution provider.
//!
//! ## Builtin models
//!
//! The catalog models in [`crate::hub`] (SwinIR etc.) are downloaded
//! artifacts; none ship with the repo today (their `sha256` entries
//! are placeholders pending the licensing decision DP#4). To keep the
//! real inference path exercisable everywhere — including CPU-only CI
//! — the crate bundles five small self-authored ONNX graphs under
//! `models/builtin/`, generated by `scripts/generate_builtin_models.py`.
//! They are classical image-processing kernels (Gaussian blend, unsharp
//! mask, linear upscale, outlier replacement, masked fill), each a few
//! hundred bytes, each pinned by a real SHA-256 digest in
//! [`BUILTIN_MODELS`]. When a catalog model artifact lands in the
//! model registry, the dispatcher prefers it; the builtin is the
//! always-available floor.
//!
//! ## Graph contract
//!
//! Every builtin graph consumes a single-channel image tensor
//! `[1, 1, H, W]` with dynamic spatial dims; the engine loops over
//! image channels. Scalar parameters (`strength`, `threshold`) are
//! graph inputs, so one graph serves the whole parameter range. The
//! masked-fill graph takes a second `[1, 1, H, W]` tensor carrying the
//! mask weights.

use astroforge_core::artifact::ContentStore;
use astroforge_core::image::F32Image;
use astroforge_core::masks::Mask;
use serde::{Deserialize, Serialize};

/// Which scalar input a builtin graph expects, if any.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BuiltinInputKind {
    /// `image` only (upscale).
    ImageOnly,
    /// `image` + `strength` scalar.
    Strength,
    /// `image` + `threshold` scalar.
    Threshold,
    /// `image` + `mask` tensor.
    Mask,
}

/// A bundled classical-kernel ONNX model. `bytes` are the ONNX
/// protobuf, embedded at compile time; `sha256` is the digest the
/// generator printed when the fixture was produced. The digest is
/// verified at session-build time so a corrupted or tampered fixture
/// fails closed instead of running.
pub struct BuiltinModel {
    pub id: &'static str,
    pub kind: BuiltinInputKind,
    pub sha256: &'static str,
    pub bytes: &'static [u8],
}

/// The bundled models, in registry order. Digests are emitted by
/// `scripts/generate_builtin_models.py`; regenerate and update this
/// table in the same commit when a graph changes.
pub const BUILTIN_MODELS: &[BuiltinModel] = &[
    BuiltinModel {
        id: "builtin-blur-blend",
        kind: BuiltinInputKind::Strength,
        sha256: "30b4c3729513f54802d00680ae6793016719f4cc40a00a7f231d220ccb1ae4f3",
        bytes: include_bytes!("../models/builtin/builtin-blur-blend.onnx"),
    },
    BuiltinModel {
        id: "builtin-sharpen-blend",
        kind: BuiltinInputKind::Strength,
        sha256: "34d34e9e75febfb3db84a5cc9ff4e1177ab003d2a9247cc8977845602c86cd85",
        bytes: include_bytes!("../models/builtin/builtin-sharpen-blend.onnx"),
    },
    BuiltinModel {
        id: "builtin-upscale-2x",
        kind: BuiltinInputKind::ImageOnly,
        sha256: "195850f85b9661fe7b3361b5c02c7b1a9ca5f453ae639082691f675ee075b7f1",
        bytes: include_bytes!("../models/builtin/builtin-upscale-2x.onnx"),
    },
    BuiltinModel {
        id: "builtin-hotpixel",
        kind: BuiltinInputKind::Threshold,
        sha256: "07589c4d911fd4820ebcd7454d04c43cb926adad2bc75786c3bcb9cc496fba97",
        bytes: include_bytes!("../models/builtin/builtin-hotpixel.onnx"),
    },
    BuiltinModel {
        id: "builtin-masked-fill",
        kind: BuiltinInputKind::Mask,
        sha256: "d1646db8b65d2fb02a6badffd596f1cb255b0cef53edfa5086fc77f077b012ea",
        bytes: include_bytes!("../models/builtin/builtin-masked-fill.onnx"),
    },
];

pub fn builtin_model(id: &str) -> Option<&'static BuiltinModel> {
    BUILTIN_MODELS.iter().find(|m| m.id == id)
}

/// Errors from the inference engine. `Ort` carries the ONNX Runtime
/// error string (the `ort` error type does not implement `Clone` /
/// `PartialEq`, so we flatten to `String` at the boundary).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum InferenceError {
    /// The fixture bytes do not match the pinned digest.
    ChecksumMismatch { expected: String, actual: String },
    /// ONNX Runtime refused the model or the run.
    Ort(String),
    /// The graph produced a shape the engine cannot map back to an
    /// image (e.g. inconsistent per-channel output dims).
    BadOutputShape(String),
    /// A required input (mask) was not supplied for this graph kind.
    MissingInput(String),
}

impl std::fmt::Display for InferenceError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            InferenceError::ChecksumMismatch { expected, actual } => write!(
                f,
                "model checksum mismatch: expected {expected}, got {actual}"
            ),
            InferenceError::Ort(e) => write!(f, "onnx runtime: {e}"),
            InferenceError::BadOutputShape(s) => write!(f, "bad output shape: {s}"),
            InferenceError::MissingInput(s) => write!(f, "missing input: {s}"),
        }
    }
}

impl std::error::Error for InferenceError {}

/// One live ONNX session bound to a specific builtin graph kind.
/// Sessions are cheap-ish to build but not free; the dispatcher builds
/// one per apply round. (A session cache keyed by model id is a
/// possible later optimisation — measure first.)
pub struct OnnxEngine {
    session: ort::session::Session,
    kind: BuiltinInputKind,
}

impl OnnxEngine {
    /// Build a session from raw ONNX bytes after verifying the digest
    /// against the pinned value. CPU execution provider only; GPU
    /// providers are compile-time features and land in P5.2.
    pub fn open_verified(
        bytes: &[u8],
        expected_sha256: &str,
        kind: BuiltinInputKind,
    ) -> Result<Self, InferenceError> {
        let actual = ContentStore::sha256_hex(bytes);
        if actual != expected_sha256 {
            return Err(InferenceError::ChecksumMismatch {
                expected: expected_sha256.to_string(),
                actual,
            });
        }
        let session = ort::session::Session::builder()
            .and_then(|mut b| b.commit_from_memory(bytes))
            .map_err(|e| InferenceError::Ort(e.to_string()))?;
        Ok(Self { session, kind })
    }

    pub fn open_builtin(model: &'static BuiltinModel) -> Result<Self, InferenceError> {
        Self::open_verified(model.bytes, model.sha256, model.kind)
    }

    /// Open a session from a downloaded catalog artifact.
    /// Catalog digests are placeholders pending DP#4, so
    /// the bytes are not digest-pinned here; the caller
    /// records the actual hash in the provenance row.
    pub fn open_catalog(bytes: Vec<u8>, kind: BuiltinInputKind) -> Result<Self, InferenceError> {
        let session = ort::session::Session::builder()
            .and_then(|mut b| b.commit_from_memory(&bytes))
            .map_err(|e| InferenceError::Ort(e.to_string()))?;
        Ok(Self { session, kind })
    }

    pub fn kind(&self) -> BuiltinInputKind {
        self.kind
    }

    /// Run the graph over every channel of `image` and restack the
    /// per-channel outputs. `strength` feeds the `strength` /
    /// `threshold` scalar input when the graph kind declares one;
    /// `mask` feeds the `mask` tensor input for masked-fill.
    ///
    /// Output dims come from the graph (the upscale graph returns
    /// `[1, 1, 2H, 2W]`); all channels must agree.
    pub fn run(
        &mut self,
        image: &F32Image,
        strength: Option<f32>,
        mask: Option<&Mask>,
    ) -> Result<F32Image, InferenceError> {
        let channels = image.channels();
        let mut out_planes: Option<(usize, usize, Vec<Vec<f32>>)> = None;
        for c in 0..channels {
            let plane = extract_plane(image, c);
            let out = self.run_plane(image.width(), image.height(), &plane, strength, mask)?;
            match &mut out_planes {
                None => out_planes = Some((out.0, out.1, vec![out.2])),
                Some((w, h, planes)) => {
                    if *w != out.0 || *h != out.1 {
                        return Err(InferenceError::BadOutputShape(format!(
                            "channel {c} produced {}x{}, expected {w}x{h}",
                            out.0, out.1
                        )));
                    }
                    planes.push(out.2);
                }
            }
        }
        let (w, h, planes) = out_planes
            .ok_or_else(|| InferenceError::BadOutputShape("image has zero channels".into()))?;
        Ok(stack_planes(w, h, &planes))
    }

    /// Run one single-channel plane through the graph. Returns
    /// `(out_w, out_h, row-major pixels)`.
    fn run_plane(
        &mut self,
        width: usize,
        height: usize,
        plane: &[f32],
        strength: Option<f32>,
        mask: Option<&Mask>,
    ) -> Result<(usize, usize, Vec<f32>), InferenceError> {
        use ort::value::Tensor;

        let img_tensor = Tensor::from_array((
            vec![1usize, 1, height, width],
            plane.to_vec().into_boxed_slice(),
        ))
        .map_err(|e| InferenceError::Ort(e.to_string()))?;

        let outputs = match self.kind {
            BuiltinInputKind::ImageOnly => self
                .session
                .run(ort::inputs![img_tensor])
                .map_err(|e| InferenceError::Ort(e.to_string()))?,
            BuiltinInputKind::Strength | BuiltinInputKind::Threshold => {
                let name = match self.kind {
                    BuiltinInputKind::Strength => "strength",
                    _ => "threshold",
                };
                let value = strength.unwrap_or(0.5);
                let scalar = Tensor::from_array((vec![1usize], vec![value].into_boxed_slice()))
                    .map_err(|e| InferenceError::Ort(e.to_string()))?;
                self.session
                    .run(ort::inputs!["image" => img_tensor, name => scalar])
                    .map_err(|e| InferenceError::Ort(e.to_string()))?
            }
            BuiltinInputKind::Mask => {
                let mask = mask.ok_or_else(|| {
                    InferenceError::MissingInput("masked-fill graph requires a mask tensor".into())
                })?;
                let mask_plane = mask_plane_for(mask, width, height);
                let mask_tensor = Tensor::from_array((
                    vec![1usize, 1, height, width],
                    mask_plane.into_boxed_slice(),
                ))
                .map_err(|e| InferenceError::Ort(e.to_string()))?;
                self.session
                    .run(ort::inputs!["image" => img_tensor, "mask" => mask_tensor])
                    .map_err(|e| InferenceError::Ort(e.to_string()))?
            }
        };

        let (shape, data) = outputs[0]
            .try_extract_tensor::<f32>()
            .map_err(|e| InferenceError::Ort(e.to_string()))?;
        let dims: Vec<usize> = shape.iter().map(|&d| d as usize).collect();
        if dims.len() != 4 || dims[0] != 1 || dims[1] != 1 {
            return Err(InferenceError::BadOutputShape(format!(
                "expected [1,1,H,W], got {dims:?}"
            )));
        }
        Ok((dims[3], dims[2], data.to_vec()))
    }
}

/// Extract channel `c` of an F32Image as a row-major `Vec<f32>`.
fn extract_plane(image: &F32Image, c: usize) -> Vec<f32> {
    let w = image.width();
    let h = image.height();
    let mut plane = Vec::with_capacity(w * h);
    for y in 0..h {
        for x in 0..w {
            plane.push(image[(c, y, x)]);
        }
    }
    plane
}

/// Restack per-channel row-major planes into an F32Image
/// (`(C, H, W)` layout).
fn stack_planes(width: usize, height: usize, planes: &[Vec<f32>]) -> F32Image {
    let mut img = F32Image::new(width, height, planes.len());
    for (c, plane) in planes.iter().enumerate() {
        for y in 0..height {
            for x in 0..width {
                img[(c, y, x)] = plane[y * width + x];
            }
        }
    }
    img
}

/// Rasterise a mask into a `width * height` row-major plane, sampling
/// with clamping when the mask dims disagree with the image dims (a
/// mask authored against a downscaled preview still applies).
fn mask_plane_for(mask: &Mask, width: usize, height: usize) -> Vec<f32> {
    let mut plane = Vec::with_capacity(width * height);
    for y in 0..height {
        for x in 0..width {
            let mx = (x as u64 * mask.width as u64 / width.max(1) as u64) as u32;
            let my = (y as u64 * mask.height as u64 / height.max(1) as u64) as u32;
            plane.push(mask.get(mx.min(mask.width - 1), my.min(mask.height - 1)));
        }
    }
    plane
}

#[cfg(test)]
mod tests {
    use super::*;
    use astroforge_core::masks::MaskKind;
    use ndarray::Array3;

    fn gradient(width: usize, height: usize) -> F32Image {
        let mut arr = Array3::<f32>::zeros((1, height, width));
        for y in 0..height {
            for x in 0..width {
                arr[(0, y, x)] = (x + y) as f32 / (width + height) as f32;
            }
        }
        F32Image::from(arr)
    }

    fn uniform(value: f32, width: usize, height: usize, channels: usize) -> F32Image {
        F32Image::from(Array3::from_elem((channels, height, width), value))
    }

    fn engine(id: &str) -> OnnxEngine {
        OnnxEngine::open_builtin(builtin_model(id).expect("builtin exists")).expect("session")
    }

    #[test]
    fn every_builtin_fixture_matches_its_pinned_digest() {
        for model in BUILTIN_MODELS {
            let actual = ContentStore::sha256_hex(model.bytes);
            assert_eq!(actual, model.sha256, "digest drifted for {}", model.id);
        }
    }

    #[test]
    fn checksum_mismatch_fails_closed() {
        let model = builtin_model("builtin-blur-blend").unwrap();
        let err = match OnnxEngine::open_verified(model.bytes, "0000", model.kind) {
            Ok(_) => panic!("mismatched digest must fail closed"),
            Err(e) => e,
        };
        assert!(matches!(err, InferenceError::ChecksumMismatch { .. }));
    }

    #[test]
    fn blur_blend_preserves_uniform_image() {
        let img = uniform(0.4, 24, 24, 1);
        let out = engine("builtin-blur-blend")
            .run(&img, Some(1.0), None)
            .unwrap();
        for y in 2..22 {
            for x in 2..22 {
                assert!((out[(0, y, x)] - 0.4).abs() < 1e-4);
            }
        }
    }

    #[test]
    fn blur_blend_reduces_variance_of_noisy_image() {
        let mut arr = Array3::<f32>::zeros((1, 32, 32));
        for y in 0..32 {
            for x in 0..32 {
                let checker = if (x + y) % 2 == 0 { 0.8 } else { 0.2 };
                arr[(0, y, x)] = checker;
            }
        }
        let img = F32Image::from(arr);
        let out = engine("builtin-blur-blend")
            .run(&img, Some(1.0), None)
            .unwrap();
        let var = |image: &F32Image| {
            let n = (image.width() * image.height()) as f32;
            let mut sum = 0.0;
            let mut sq = 0.0;
            for y in 0..image.height() {
                for x in 0..image.width() {
                    let v = image[(0, y, x)];
                    sum += v;
                    sq += v * v;
                }
            }
            (sq / n) - (sum / n).powi(2)
        };
        assert!(var(&out) < var(&img) * 0.5);
    }

    #[test]
    fn blur_blend_at_zero_strength_is_identity() {
        let img = gradient(16, 16);
        let out = engine("builtin-blur-blend")
            .run(&img, Some(0.0), None)
            .unwrap();
        for y in 0..16 {
            for x in 0..16 {
                assert!((out[(0, y, x)] - img[(0, y, x)]).abs() < 1e-6);
            }
        }
    }

    #[test]
    fn sharpen_blend_increases_local_contrast() {
        // A single bright pixel on a dark field: the unsharp mask must
        // raise the peak above the source value.
        let mut img = uniform(0.1, 24, 24, 1);
        img[(0, 12, 12)] = 0.9;
        let out = engine("builtin-sharpen-blend")
            .run(&img, Some(1.0), None)
            .unwrap();
        assert!(out[(0, 12, 12)] > 0.9 + 1e-3);
    }

    #[test]
    fn upscale_2x_doubles_spatial_dims() {
        let img = gradient(8, 6);
        let out = engine("builtin-upscale-2x").run(&img, None, None).unwrap();
        assert_eq!(out.width(), 16);
        assert_eq!(out.height(), 12);
        assert_eq!(out.channels(), 1);
        // Linear upscale of a linear ramp stays monotonic along x.
        for y in 0..12 {
            for x in 1..16 {
                assert!(out[(0, y, x)] >= out[(0, y, x - 1)] - 1e-6);
            }
        }
    }

    #[test]
    fn hotpixel_replaces_only_the_spike() {
        let mut img = uniform(0.2, 16, 16, 1);
        img[(0, 8, 8)] = 1.0;
        let out = engine("builtin-hotpixel")
            .run(&img, Some(1.5), None)
            .unwrap();
        assert!(
            out[(0, 8, 8)] < 0.4,
            "spike must collapse to the local mean"
        );
        // An interior pixel far from the spike is untouched. (Border
        // pixels are excluded: ONNX Conv zero-pads, which drags border
        // means down and can trip the threshold there. The dispatcher's
        // tile overlap blending absorbs border effects in practice.)
        assert!((out[(0, 4, 8)] - 0.2).abs() < 1e-4);
    }

    #[test]
    fn masked_fill_only_touches_masked_region() {
        let mut img = uniform(0.2, 16, 16, 1);
        img[(0, 8, 8)] = 1.0;
        let mut mask = Mask::zeros(16, 16, MaskKind::User, "test".into());
        mask.set(8, 8, 1.0);
        let out = engine("builtin-masked-fill")
            .run(&img, None, Some(&mask))
            .unwrap();
        // Masked pixel is pulled toward the local mean (0.2).
        assert!(out[(0, 8, 8)] < 0.9);
        // Unmasked pixels pass through.
        assert!((out[(0, 0, 0)] - 0.2).abs() < 1e-4);
        assert!((out[(0, 4, 4)] - 0.2).abs() < 1e-4);
    }

    #[test]
    fn masked_fill_without_mask_errors() {
        let img = uniform(0.2, 8, 8, 1);
        let err = engine("builtin-masked-fill")
            .run(&img, None, None)
            .unwrap_err();
        assert!(matches!(err, InferenceError::MissingInput(_)));
    }

    #[test]
    fn multichannel_images_run_per_channel() {
        let img = uniform(0.5, 12, 12, 3);
        let out = engine("builtin-blur-blend")
            .run(&img, Some(0.7), None)
            .unwrap();
        assert_eq!(out.channels(), 3);
        for c in 0..3 {
            assert!((out[(c, 6, 6)] - 0.5).abs() < 1e-4);
        }
    }

    #[test]
    fn mask_plane_resamples_mismatched_dims() {
        let mut mask = Mask::zeros(4, 4, MaskKind::User, "test".into());
        mask.set(0, 0, 1.0);
        let plane = mask_plane_for(&mask, 8, 8);
        assert_eq!(plane.len(), 64);
        // Top-left quadrant samples mask (0,0) = 1.0; opposite corner 0.0.
        assert!((plane[0] - 1.0).abs() < 1e-6);
        assert!((plane[63] - 0.0).abs() < 1e-6);
    }
}
