<!--
  CR-05 P1 — Auto-mode smoke panel.

  This component renders a PipelinePlan generated by the Rust
  `create_pipeline_plan` Tauri command as a human-readable processing
  journey (per CR-05 §2.1: "M31 — Deep Sky OSC / ✓ Calibrate /
  ✓ Debayer / …"). It is a thin presentation layer; the wizard
  ProcessWorkspace continues to own execution through P2.

  Wiring ProcessWorkspace to import this panel is intentionally a
  separate P1.5 PR (the wizard path stays untouched for P1). For P1,
  this component exists so that:
    1. The IPC + store chain is end-to-end type-checked.
    2. The visual contract ("Auto produces this layout") is on disk
       before P2 wires the runner.

  Props:
    projectId, sessionId — required to call `generateAutoPlan`.
-->
<script lang="ts">
  import {
    activePlan,
    generateAutoPlan,
    generateExpertPlan,
    generateGuidedPlan,
    humanReadablePlan,
    lastError,
    planGenerationStatus,
    progressFraction,
    requiredStages,
    optionalStages,
  } from "../lib/pipeline-plan-store";

  export let projectId: string;
  export let sessionId: string;

  let selectedMode: "auto" | "guided" | "expert" = "auto";

  async function onGenerate() {
    if (selectedMode === "auto") {
      await generateAutoPlan(projectId, sessionId);
    } else if (selectedMode === "guided") {
      await generateGuidedPlan(projectId, sessionId);
    } else {
      await generateExpertPlan(projectId, sessionId);
    }
  }
</script>

<section class="auto-plan-panel" aria-label="Auto-mode pipeline plan">
  <header class="panel-header">
    <h2 class="font-display">Auto-mode pipeline plan</h2>
    <p class="font-body panel-description">
      Generates a concrete, dataset-aware processing workflow from the
      CR-04 Session Understanding. P1 ships the generation path; P2
      will wire execution.
    </p>
  </header>

  <div class="controls">
    <label class="font-label" for="mode-select">Mode</label>
    <select id="mode-select" bind:value={selectedMode} class="font-body">
      <option value="auto">Auto</option>
      <option value="guided">Guided</option>
      <option value="expert">Expert</option>
    </select>
    <button
      type="button"
      class="primary-action font-label"
      on:click={onGenerate}
      disabled={$planGenerationStatus === "generating"}
    >
      {$planGenerationStatus === "generating"
        ? "Generating…"
        : "Generate plan"}
    </button>
  </div>

  {#if $lastError}
    <p class="error font-body" role="alert">{$lastError}</p>
  {/if}

  {#if $activePlan}
    <div class="plan-card">
      <div class="plan-header font-body">
        <span class="plan-target">{$activePlan.target_type.replace(/_/g, " ")}</span>
        <span class="plan-mode">{$activePlan.mode}</span>
        <span class="plan-progress">
          {Math.round(progressFraction($activePlan) * 100)}% enabled
        </span>
      </div>

      <pre
        class="human-readable font-body"
        aria-label="Human-readable processing journey"
      >{$humanReadablePlan}</pre>

      <details class="stage-details">
        <summary class="font-label">Stage detail ({$activePlan.stages.length})</summary>
        <div class="stage-grid">
          <div class="stage-column">
            <h3 class="font-label">Required</h3>
            <ul class="stage-list">
              {#each requiredStages($activePlan) as stage (stage.stage_id)}
                <li class="stage-item required">
                  <span class="stage-label font-body">{stage.label}</span>
                  <span class="stage-type font-label">{stage.stage_type}</span>
                </li>
              {/each}
            </ul>
          </div>
          <div class="stage-column">
            <h3 class="font-label">Optional</h3>
            <ul class="stage-list">
              {#each optionalStages($activePlan) as stage (stage.stage_id)}
                <li class="stage-item optional">
                  <span class="stage-label font-body">{stage.label}</span>
                  <span class="stage-type font-label">{stage.stage_type}</span>
                </li>
              {/each}
            </ul>
          </div>
        </div>
      </details>
    </div>
  {:else}
    <p class="placeholder font-body">
      No plan generated yet. Pick a mode and click <em>Generate plan</em>.
    </p>
  {/if}
</section>

<style>
  .auto-plan-panel {
    display: flex;
    flex-direction: column;
    gap: var(--sp-md);
    padding: var(--sp-lg);
    background: var(--surface-container);
    border-radius: var(--radius-md);
  }
  .panel-header h2 {
    margin: 0 0 var(--sp-xs) 0;
    font-size: 1.1rem;
  }
  .panel-description {
    margin: 0;
    color: var(--on-surface-variant);
    font-size: 0.85rem;
  }
  .controls {
    display: flex;
    align-items: center;
    gap: var(--sp-sm);
  }
  .controls label {
    color: var(--on-surface-variant);
  }
  .controls select {
    background: var(--surface-container-high);
    color: var(--on-surface);
    border: 1px solid var(--outline);
    border-radius: var(--radius-sm);
    padding: var(--sp-xs) var(--sp-sm);
  }
  .primary-action {
    margin-left: auto;
    background: var(--primary);
    color: var(--on-primary);
    border: none;
    border-radius: var(--radius-full);
    padding: var(--sp-xs) var(--sp-md);
    cursor: pointer;
  }
  .primary-action:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .error {
    color: #ff8a80;
    background: rgba(229, 57, 53, 0.12);
    padding: var(--sp-xs) var(--sp-sm);
    border-radius: var(--radius-sm);
  }
  .plan-card {
    display: flex;
    flex-direction: column;
    gap: var(--sp-sm);
    background: var(--surface-container-low);
    border-radius: var(--radius-sm);
    padding: var(--sp-md);
  }
  .plan-header {
    display: flex;
    gap: var(--sp-md);
    color: var(--on-surface-variant);
    font-size: 0.85rem;
  }
  .plan-progress {
    margin-left: auto;
  }
  .human-readable {
    margin: 0;
    padding: var(--sp-sm);
    background: var(--surface);
    color: var(--on-surface);
    border-radius: var(--radius-sm);
    font-family: var(--font-mono);
    font-size: 0.85rem;
    white-space: pre-wrap;
  }
  .stage-details summary {
    cursor: pointer;
    color: var(--on-surface-variant);
  }
  .stage-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: var(--sp-md);
    margin-top: var(--sp-sm);
  }
  .stage-column h3 {
    margin: 0 0 var(--sp-xs) 0;
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--on-surface-variant);
  }
  .stage-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: var(--sp-xs);
  }
  .stage-item {
    display: flex;
    justify-content: space-between;
    padding: var(--sp-xs) var(--sp-sm);
    background: var(--surface-container);
    border-radius: var(--radius-sm);
  }
  .stage-item.required {
    border-left: 3px solid var(--primary);
  }
  .stage-item.optional {
    border-left: 3px solid var(--on-surface-variant);
    opacity: 0.85;
  }
  .stage-type {
    color: var(--on-surface-variant);
    font-size: 0.7rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }
  .placeholder {
    color: var(--on-surface-variant);
    font-style: italic;
  }
</style>